let messages = [
    'I am the smoke that smokes Smoked Oysters.',
    'I am the hairball that clogs your drains.',
    'I am the slug that slimes your Begonias.',
    'I am the scourge that pecks at your nightmares.',
    'I am The Batteries That Are Not Included.',
    'I am the Batteries That Are Not Included.',
    'I am the low ratings that cancel your program.',
    'I am the Check Writer In The Cash Only Line.',
    'I am the Weirdo Who Sits Next To You On The Bus.',
    'I am the Fast Food That Comes Back To Haunt You.',
    'I am The Neurosis That Requires A $500 An Hour Shrink.',
    'I am the Stain That Can’t Be Rubbed Out.',
    'I am the Ingrown Toenail On The Foot Of Crime.',
    'I am the Grade Curve That Gives You An F.',
    'I am the Auditor Who Wants To Look At Your Books.',
    'I am the Repair Man Who Tells You Your Warranty Has Run Out.',
    'I am the Rhinestones On The Jump Suit Of Justice.',
    'I am the Zit That Forms When You’ve Got A Really Big Date.',
    'I am the Widget Missing From The Easy To Assemble Swing Set.',
    'I am the Chill That Runs Up Your Spine.',
    'I am the Jailer Who Throws Away The Key. I Am… Feeling Really Stupid. Boy I Hate It When I’m Early.',
    'I am the Bubble Gum That Clings To Your Shoe.',
    'I am the Pin That Will Burst Your Bubble.',
    'I am the Surprise In Your Cereal Box.',
    'I am the Raspberry Seed You Can’t Floss Out.',
    'I am the Combination Lock On The Vault Of Justice.',
    'I am the Cloud That Rains On Your Hit Parade.',
    'I am the $10 Service Charge On All Return Checks.',
    'I am the Switch That Derails Your Train.',
    'I am the Single Career Man All Women Want To Date.',
    'I am the Hair In The Lens Of Your Projector.',
    'I am the Metal Key On The Sardine Can Of Justice.',
    'I am the Principal You Were Sent To See.',
    'I am the Flea You Cannot Flick.',
    'I am the Editor That Leaves You On The Cutting Room Floor.',
    'I am the Quality Time That Ruins Your Playtime.',
    'I am the Smallest, Weakest Thing In The Whole Place. And I Am Also Outta Here!',
    'I am the Termite That Devours Your Floorboards.',
    'I am the Pit Bull That Bites The Ankle Of Crime.',
    'I am the Lollipop That Sticks In Your Hair.',
    'I am the Butter That Burns In Your Pan.',
    'I am the Scourge That Pecks At Your, Uh, Your Nightmares, Ummm',
    'I am the Limestone That Petrifies Your Bones.',
    'I am the Eraser That Rubs Out The Typos Of Crime.',
    'I am the Water Balloon That Lands Right On Your Head.',
    'I am the Pestilent Blister That Bursts In Your Boot.',
    'I am the Blown Fuse That Blacks You Out.',
    'I am the Clock Cleaner Who Will Ring Your Chimes.',
    'I am the Icky Bug That Crawls Up Your Trouser Leg.',
    'I am the Muddy Shoes That Track The Linoleum Of Crime.',
    'I am the Spider Who Nips At Your Neck.',
    'I am the Little Mouse That Eats Your Cheese.',
    'I am the Moth That Seeks Your Porch Light.',
    'I am the Pencil That Breaks From Signing Too Many Autographs.',
    'I am the Clipper That Trims Your Hedges.',
    'I am the Squeaky Brakes That Stick---Oh Nuts!',
    'I am the Splash Guard On Your Flying Saucer Windshield.',
    'I am the Number 90 Sunblock That Will Stop Your Burn.'
];

module.exports = function (message) {
    let random = messages[Math.floor(Math.random() * messages.length)];

    message.channel.send(random);
};
